# Generated by Django 4.0 on 2022-02-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicprice',
            old_name='time',
            new_name='date',
        ),
    ]
