# Generated by Django 4.0 on 2022-02-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboards', '0002_rename_time_historicprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicprice',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicprice',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicprice',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicprice',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
