# Generated by Django 4.0.3 on 2022-04-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboards', '0011_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='choice',
            new_name='status',
        ),
    ]
