# Generated by Django 4.0 on 2022-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='name',
            field=models.CharField(default=0.0, max_length=200),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='signal',
            field=models.CharField(default=0.0, max_length=200),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='symbol',
            field=models.CharField(default=0.0, max_length=5),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='gain_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='shares_owned',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together={('user', 'symbol')},
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='stock',
        ),
    ]
