# Generated by Django 4.0 on 2022-02-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0002_alter_stockportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='shares_owned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
