# Generated by Django 4.0 on 2022-02-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0003_alter_stockportfolio_shares_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='signal',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='symbol',
            field=models.CharField(default='', max_length=1),
        ),
    ]
