# Generated by Django 4.0 on 2022-02-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0004_alter_stockportfolio_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=1)),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('signal', models.CharField(default='', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolios.portfoliouser')),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
